### ISSUE TITLE
Will we have to make app only for android or for both android and IOS?

### ISSUE THREAD

**Issue by shreya2feb** [scorelab/LabelLab#1]

**Comment by RishabhMaheshwary** [comment]
Actually the app is to be built in react native. It will run on both android and ios.

**Comment by RishabhMaheshwary** [comment]
@charithccmc can you help us on how to get started ?

**Comment by shreya2feb** [comment]
@RishabhMaheshwary but building in React Native is not that easy, I think We have to go for Android Application first than move to React Native.

Dear @charithccmc,
I can go for what you say, I have expertise in both React Native and Android Studio

**Comment by RishabhMaheshwary** [comment]
@shreya2feb yeah might be, but I have implemented react web with django backend.
If you are going for the mobile app than I can start on the web app because they are 2 separate projects in GSOC list.
@charithccmc what do you say can I start with the web app ?

**Comment by OshanIvantha** [comment]
Hi @shreya2feb and @RishabhMaheshwary! We are really glad that you are enthusiastic about the project. Please email me at oshan.ivantha@gmail.com with your ideas regarding the implementation and maybe we can start with a pre-gsoc task! 😉

**Comment by RishabhMaheshwary** [comment]
@OshanIvantha I already emailed you in the morning.

**Comment by shreya2feb** [comment]
@Oshanlvantha I started the work and already created a pull request, currently I'm writting my pre proposal, I'll mail you soon as I complete my proposal.

**Comment by ivantha** [comment]
Please join our Gitter channel and check out the challenge task before implementing anything 🙂 
https://gitter.im/scorelab/LabelLab

**Comment by shreya2feb** [comment]
@shreya2feb Please join our Gitter channel and check out the challenge task before implementing anything 🙂


> @shreya2feb Please join our Gitter channel and check out the challenge task before implementing anything 🙂
> https://gitter.im/scorelab/LabelLab

@ivantha Thanks for your consideration, I joined the Gitter channel and also went through the doc. I'll convert the till date work into React Native and Nodejs.

**Comment by vinay72** [comment]
@RishabhMaheshwary According to the Official GSOC-2019 list of project ideas of Score Lab , there is one Idea which is on Implement the Label Lab Web Application . I want to work on this Idea and want to take part in GSOC-2019 .
