### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by robinranjan** [scorelab/LabelLab#111]
as per your readme file
i clonet he repository, but to setup react js server there is no npm installation file present. can you help me setup.

**Comment by Tushar19varshney** [comment]
There is file called `package.json` file which handles all the packages and frontend server details. You just have to run `npm i` for installation, then you can start server by running `npm start`.

**Comment by APushpendra08** [comment]
TOKEN_VALUE does not exist in /constants/index.js but is being imported from /utils/FetchAPI.js.It is giving error while doing npm start.

**Comment by Tushar19varshney** [comment]
This issue is now fixed.
