### ISSUE TITLE
Error in MongoDB Connection String

### ISSUE THREAD

**Issue by msk4862** [scorelab/LabelLab#112]
**ERROR:**
Inside lablabel-server folder:
When I tried to run nodemon server, It shows <br> `MongoParseError: Invalid connection string`<br>
When I added `mongodb://` prefix in mongoURI i.e. `mongodb://localhost:27017/my-db`, It fixed the problem.

**POSSIBLE SOLUTION:**
So, I think  `mongodb://` prefix is also required in mongodb connection string.

**Comment by UdeshUK** [comment]
MongoDB URI should be generated using the env variables in ```.env```. You can refer ```.env.example``` for more info.
