### ISSUE TITLE
User ML model section 

### ISSUE THREAD

**Issue by kunalbhatia18** [scorelab/LabelLab#113]
- [x] The images which were taken should have a function inside the path tracking feature to track the location of the images.

- [x] User should be able to switch/choose between various ML models for testing their project.

**Comment by carpecodeum** [comment]
hey just a heads up i am already working on the path tracking issue and i have come close on solving it if you could avoid the first task and work on the second one it would be great :)

**Comment by kunalbhatia18** [comment]
Ya sure @carpecodeum I won't work on the first task. No issues
