### ISSUE TITLE
In the README.md file to run labellabs-client

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/LabelLab#114]
**Describe the bug**
there are no instructions on how to run the clientside-server
it should say `Run the Node server in the labellab-client folder:` instead of 
`Run the Node server in the labellab-server folder:`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by UdeshUK** [comment]
@carpecodeum Node server of backend server should be run on labellab-server before client's server. Reopen the issue if there is a further issue.
