### ISSUE TITLE
Cannot import TOKEN_VALUE from ../constants/index

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/LabelLab#116]
**Describe the bug**
this comes written in the console when we first run our client-side server.

**To Reproduce**
1. Run 'npm start in labellabs-client folder'
see error

**Expected behavior**
the client side server should have started without any errors.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOs Catalina
 - Browser [e.g. chrome, safari]chrome

**Comment by Rupeshiya** [comment]
@carpecodeum  This error is because of 'TOKEN_VALUE' is not exported from '../constants/index'.
TOKEN_TYPE should be imported

**Comment by carpecodeum** [comment]
@Rupeshiya yes i have fixed this

**Comment by Rupeshiya** [comment]
@carpecodeum are you contributing to this org?
Where you guys are discussing about the issues or fixes?
I tried a lot to communicate, but everyone seems to be inactive.

**Comment by UdeshUK** [comment]
> @carpecodeum are you contributing to this org?
> Where you guys are discussing about the issues or fixes?
> I tried a lot to communicate, but everyone seems to be inactive.
> Plz let me know, if you find any active maintainer

@Rupeshiya you can join the [Gitter Group](https://gitter.im/scorelab/LabelLab) :)

**Comment by UdeshUK** [comment]
Closing the issue since it's fixed
