### ISSUE TITLE
Error in mongo URI

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/LabelLab#118]
**Describe the bug**
the current URI given is not correct. It is missing a condition when there is no username and password set for the database also 'mongodb://'+ dbUser + ':' + dbPass + '@' + dbCluster + '/' + `dbName` is the correct form rather than `dbHost` + '://'+ dbUser + ':' + dbPass + '@' + dbCluster + '/' + dbName

**Comment by mayursamnani36** [comment]
@carpecodeum  I checked `dbURI.js` and i think everything mentioned above is corrected already and this issue can be closed.
