### ISSUE TITLE
Update the readme.md with the correct steps to run server and other.

### ISSUE THREAD

**Issue by Rupeshiya** [scorelab/LabelLab#120]
**Describe the bug**
Update the readme.md with the correct steps to run the server and other. As of now, before installing the dependencies it's starting the server using npm start.

**To Reproduce**
1. Go to 'Readme.md'
2. And check the steps to run server-side
3. See 

**Expected behavior**
Before starting, install dependencies.

Also provide some information about the .env file. i.e what should be added and what may be ignored

**Comment by mayursamnani36** [comment]
Hello i would i like to make changes to the Readme file as i just setup my local environment and i had faced issues so i think i can describe them correctly.

**Comment by Rupeshiya** [comment]
Sure @mayursamnani36, You can go ahead.

**Comment by mayursamnani36** [comment]
@Rupeshiya I just made changes in README.md in a new branch on my local machine. Should i send a pull request or do i need to get it reviewed my someone. I am new to open source and still learning how things work. Thank you.

**Comment by Rupeshiya** [comment]
> @Rupeshiya I just made changes in README.md in a new branch on my local machine. Should i send a pull request or do i need to get it reviewed my someone. I am new to open source and still learning how things work. Thank you.

@mayursamnani36 You can send the PR. Maintainers will review your PR, and if there will be any changes required then they you guide you to do so.
