### ISSUE TITLE
Hash the password before saving to db to prevent security issue

### ISSUE THREAD

**Issue by Rupeshiya** [scorelab/LabelLab#121]
**Is your feature request related to a problem? Please describe.**
Hash the password before saving to DB to prevent the security issue

**Describe the solution you'd like**
Use bcrypt.js to hash the password and after that save the password 
```
const bcrypt = require('bcryptjs');
bcrypt.genSalt(10, (err, salt)=>{
   bcrypt.hash(newuser.password,salt, (err, hash)=>{
     newUser.password = hash;
    newuser.save(); 
  });
});
```
**Describe alternatives you've considered**
Or can use other algo to hash like SHA-256 to hash manually and then assign it to password

**Comment by Rupeshiya** [comment]
Can I take this and fix ?

**Comment by carpecodeum** [comment]
this is already implemented under the user model
