### ISSUE TITLE
Fix reference to error view

### ISSUE THREAD

**Issue by JosephSemrai** [scorelab/LabelLab#123]
**Describe the bug**
Upon an error, the server will encounter an exception as it fails to locate 'error.ejs' referred to simply as 'error'.

**To Reproduce**
1. Start the server
2. Send any request that results in the error page to be rendered

**Expected behavior**
The error page should be rendered (error.ejs in views)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version [e.g. 22]: 79

**Comment by carpecodeum** [comment]
hey i noticed this issue still exists can i work on this? @JosephSemrai

**Comment by JosephSemrai** [comment]
Feel free! I've addressed it in the testing branch, but it has not been fixed in a dedicated branch.

**Comment by mayursamnani36** [comment]
@JosephSemrai  i fixed the issue but it was just changing one line of code so should i send a pull request for it ?

**Comment by JosephSemrai** [comment]
@mayursamnani36 Feel free to make the dedicated pull request.
I had changed the line as part of another pull request, but it might be better to keep things separated.

**Comment by mayursamnani36** [comment]
okay @JosephSemrai
