### ISSUE TITLE
Improving the UI of labels route

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/LabelLab#141]
**Describe the bug**
the create new label and the create buttons are at very odd positions. I am trying to make them look more appealing. also the the upcoming submit button also does not have any bottom-margin.
**To Reproduce**
1. Go to 'one of your projects'
2. Click on 'project labels'
3. See error

**Expected behavior**
a visually appealing position of create label button and create new label button
**Screenshots**
<img width="1396" alt="Screenshot 2019-12-24 at 11 49 36 PM" src="https://user-images.githubusercontent.com/43586052/71422629-a5ba4d00-26a9-11ea-9f50-5370658eec77.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOs
 - Browser [e.g. chrome, safari] chrome

**Additional context**

**Comment by 2knal** [comment]
@carpecodeum, is this issue up for grabs?
I would like to work on it!

**Comment by carpecodeum** [comment]
@2knal yes sure you can work on it
