### ISSUE TITLE
UI fixes in the dashboard

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/LabelLab#142]
**Describe the bug**
there are some UI issues in the dashboard like not appropriate spacing is provided between menus and the project cards
**To Reproduce**
1. Go to 'dashboard'
2. try to resize your browser window

**Expected behavior**
there should have been left some margin between those two

**Screenshots**
<img width="268" alt="Screenshot 2019-12-25 at 12 03 57 AM" src="https://user-images.githubusercontent.com/43586052/71422739-5cb6c880-26aa-11ea-8a5e-21e787bc790e.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]MacOs
 - Browser [e.g. chrome, safari]Chrome

**Additional context**
i will provide additional responsive UI changes if i find any

**Comment by mayursamnani36** [comment]
working on it

**Comment by carpecodeum** [comment]
hey @mayursamnani36 i am currently working on it if you could find another issue please :)
