### ISSUE TITLE
the image link does not seem to be working

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/LabelLab#145]
**Describe the bug**
on the project images tab when an image is clicked the image does not lead to its 'static/uploads/' link 

**To Reproduce**
1. Go to 'the project image tab'
2. Click on 'one of the images'

**Expected behavior**
this should probably show the image along with its labels.

**Screenshots**

**Additional context**
i think that the link is itself leading to nowhere I'll look into it though.

**Comment by carpecodeum** [comment]
@Tushar19varshney hey can you please tell me where should one be directed to after clicking an image?

**Comment by laksh22** [comment]
@carpecodeum I think the intended functionality was to just open up the image. I have found a solution for this issue so is it alright if I make a pull request regarding this?

**Comment by carpecodeum** [comment]
@laksh22 yes sure!
