### ISSUE TITLE
HotKeysPanel not opening on clicking the open HotKeys button

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/LabelLab#150]
**Describe the bug**
when we click the hotkey button in the sidebar it does not respond at all.

**To Reproduce**
1. Go to 'the labler'
2. Click on 'the hotkeyicon'
3. See error

**Expected behavior**
the hotkeyspanel should have opened

**Screenshots**
<img width="580" alt="Screenshot 2019-12-25 at 11 42 44 PM" src="https://user-images.githubusercontent.com/43586052/71449459-0497c900-2773-11ea-864f-ef93d8a53a76.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]MacOs

**Additional context**

**Comment by Rupeshiya** [comment]
@carpecodeum A humble request to you, Please take one issue at a time and if you are done with that then go ahead with other issues.
Currently, I am getting all the issues where you have written "I am working on it"
@Tushar19varshney Please add some guidance in the contributing.md

**Comment by carpecodeum** [comment]
hey @Rupeshiya the internet connectivity in my region has not been upto the mark quite recently and therefore i am not being able to get any work done. i am working on these issues for very long and would appreciate you understanding my situations and finding more issues. I am sure there are more!

**Comment by Rupeshiya** [comment]
@carpecodeum I can understand the situation, and also want to clear you that there lots of works to do or issues to fix. I can pick any. But the way you open the issues and assigning that to yourself instead of completing one doesn't seem professional to me.
But as you wish, you can continue as per your want, 
I will not disturb you from next time for sure.
Best of luck
Happy coding!!

**Comment by laksh22** [comment]
Is anyone working on this? If not, I have implemented a solution for this issue.

**Comment by carpecodeum** [comment]
> Is anyone working on this? If not, I have implemented a solution for this issue.

Yes sure you may make a pr for this. :)
