### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by Rupeshiya** [scorelab/LabelLab#152]
**Is your feature request related to a problem? Please describe.**
As of now, there are only the unit tests for auth routes and project routes.

**Describe the solution you'd like**
There should be tests for each route.

**Describe alternatives you've considered**
Implement unit tests using Mocha and chai.js

**Additional context**
It will improve the quality of the code.

**Comment by Rupeshiya** [comment]
@Tushar19varshney Please review the issue and let me know, if I should add more tests.

**Comment by carpecodeum** [comment]
Hey @Rupeshiya i was underway writing unit tests for label, image as well as other routes just giving you a heads up that I'm already working on resolving this so that there is no confussion

**Comment by Rupeshiya** [comment]
@carpecodeum Please open the issue first and then comment down to the issues that you are working on it.
How anyone can know that you are working on anything?
Was there any issue already related to unit test and you took that?

**Comment by Rupeshiya** [comment]
@Tushar19varshney It's a request, please add some guidence to contribute in contributing.md. So that it can be avoided.

**Comment by carpecodeum** [comment]
@Rupeshiya there was not an in general issue for adding more tests but still some have contributed to this issue because it is so ambiguous.Like there is a PR of tests for Label routes. Now if you want I can open an issue about the Tests I have been working on to make things more clear.

**Comment by Rupeshiya** [comment]
@carpecodeum Since I have already created this issue, so you can take this up and move ahead.

**Comment by carpecodeum** [comment]
okay @Rupeshiya

**Comment by Tushar19varshney** [comment]
Before starting anything please make sure that you have informed with creating an issue, then making a PR. It would be much more professional.

**Comment by carpecodeum** [comment]
@Tushar19varshney i'll be sure of that next time
