### ISSUE TITLE
Use Mockgoose instead of deleting entries from database everytime while testing

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/LabelLab#154]
**Is your feature request related to a problem? Please describe.**
we always delete our created entries from our database after the tests on every route instead we could use mockgoose to automatically do that for us and it is uses the memory store which does not have persistence. And also our tests should be independent of the development database. So, using this would be a good practice 
**Describe the solution you'd like**
use mockgoose to provide a wrapper around our development database and make our development database independent from the changes within our tests also, automating the delete queries after every test.

**Additional context**
i would love to know to opinions of the maintainers here!

**Comment by carpecodeum** [comment]
@Tushar19varshney please review this proposed feature and let me know if i can implement it!

**Comment by Tushar19varshney** [comment]
@carpecodeum You can go ahead with that :+1:
