### ISSUE TITLE
Cluttered dashboard navbar in mobile view

### ISSUE THREAD

**Issue by laksh22** [scorelab/LabelLab#164]
**Describe the bug**
In mobile view, the dashboard navbar is very cluttered and hard to use.

**To Reproduce**
1. Open the dashboard.
2. Decrease the viewport width to any value less than `760px`.

**Expected behavior**
Only the most important elements of the navbar should be shown in mobile view and elements should not overlap.

**Screenshots**

![MobileViewNavbar](https://user-images.githubusercontent.com/9462834/71547996-96027780-29cd-11ea-916f-af8274eb99b0.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79

**Comment by laksh22** [comment]
@Tushar19varshney could you let me know which elements of the navbar should be kept in mobile view and which ones can be removed? I'll get started on this issue once I have this information.

**Comment by Tushar19varshney** [comment]
@laksh22 You can create a hamburger for devices having a width less than 768px :+1:
