### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by Tushar19varshney** [scorelab/LabelLab#181]
**Is your feature request related to a problem? Please describe.**
404 page can be used for redirecting user from invalid URL.

**Comment by Rupeshiya** [comment]
@Tushar19varshney , should I add 404 page and redirect them to that 404 page on invalid URL?

**Comment by raghav4** [comment]
I'm interested to work on this issue and I've started to work on this, it'd be complete in few time.

**Comment by raghav4** [comment]
@Tushar19varshney , I think I am interested in this issue, I am currently working on this now.
