### ISSUE TITLE
npm install in docker installation 

### ISSUE THREAD

**Issue by cjprogamer** [scorelab/LabelLab#205]
**Bug**
When I run the command `docker-compose up` in the project root, It gives this error.

![7](https://user-images.githubusercontent.com/41909955/72158765-d4a21580-336f-11ea-8a55-b7fe99989c1e.PNG)

**To Reproduce**
1. Go to the project root
2. Run Docker-compose up
3. See error

**Expected behavior**
Building the project successfully. 

**Desktop**
 - OS: Windows 10 1903
 - Browser: Google Chrome
 - Google Chrome Version: 79.0.3945.117

- Node: v13.5.0

- Docker version: 19.03.5

**Additional context**
After running `npm install` in labellab-client folder can solve the issue.

**Comment by UdeshUK** [comment]
@cjprogamer you should set up ```.env``` with the correct config in order to run the backend server. Refer ```.env.example``` file to find the required configs. Let's know if there are any issues with that. :)

**Comment by UdeshUK** [comment]
Reopen if there are any issues regarding this.
