### ISSUE TITLE
Build failed during "flutter run" inside labellab_mobile

### ISSUE THREAD

**Issue by Raj2367** [scorelab/LabelLab#219]
**Describe the bug**
Build failed during "flutter run" inside labellab_mobile

**To Reproduce**
1. Go to 'labellab_mobile'
2. run 'flutter run'
3. See error

**Expected behavior**
it should run the project

**Error**
Compiler message:

lib/data/remote/labellab_api_impl.dart:5:8: Error: Error when reading 'lib/config.dart': The system cannot find the file specified.

import 'package:labellab_mobile/config.dart';

       ^

../../../Documents/flutter_windows_v1.12.13+hotfix.5-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.8.0/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.

  ImageStreamCompleter load(CachedNetworkImageProvider key) {

                       ^

../../../Documents/flutter_windows_v1.12.13+hotfix.5-stable/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').

  ImageStreamCompleter load(T key, DecoderCallback decode);

                       ^

lib/data/remote/labellab_api_impl.dart:27:34: Error: Getter not found: 'API_BASE_URL'.

  static const String BASE_URL = API_BASE_URL;

                                 ^^^^^^^^^^^^

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null

build failed.

FAILURE: Build failed with an exception.

* Where:

Script 'C:\Users\user\Documents\flutter_windows_v1.12.13+hotfix.5-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:

Execution failed for task ':app:compileFlutterBuildDebug'.

> Process 'command 'C:\Users\user\Documents\flutter_windows_v1.12.13+hotfix.5-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 52s
Running Gradle task 'assembleDebug'...                            361.6s (!)
Gradle task assembleDebug failed with exit code 1

**Smartphone (please complete the following information):**
 - Device: Asus Zenfone
 - Android version : 9
 - IDE : Android Studio 3.5.3

**Additional context**
I solve this problem by upgrading the dependency "cached_network_image" from "cached_network_image-0.8.0" to "cached_network_image-2.0.0"

**Comment by UdeshUK** [comment]
@Raj2367 you have to configure the ```lib/config.dart``` using the format provided in ```lib/config_example.dart```. This includes the ```API_BASE_URL``` which is the URL to the backend server.

**Comment by UdeshUK** [comment]
> **Additional context**
> I solve this problem by upgrading the dependency "cached_network_image" from "cached_network_image-0.8.0" to "cached_network_image-2.0.0"

This is true, there is an issue in cached_network_image dependency. This is fixed on #220

**Comment by Raj2367** [comment]
@UdeshUK There is no documentation about API_BASE_URL. So please guide me what to put in API_BASE_URL.

**Comment by UdeshUK** [comment]
Yes, steps for this configuration are not straightforwardly mentioned in the ```README.md```. But it says "Configure the lib/config.dart using the format provided in lib/config_example.dart.".  And the ```API_BASE_URL``` should be set with the base URL of the ```labellab-server```

**Comment by UdeshUK** [comment]
Reopen if there are any issues regarding this.
