### ISSUE TITLE
No way to remove profile picture once set

### ISSUE THREAD

**Issue by mayursamnani36** [scorelab/LabelLab#257]
**Is your feature request related to a problem? Please describe.**
When we upload a profile picture and after that if we want to remove it then we cant do as there is no button.

**Describe the solution you'd like**
There should be a button at the profile page near the edit button to remove the currently set profile picture.

**Describe alternatives you've considered**
No alternatives for this.

**Additional context**
Would like a review from maintainers about this issue
![Screenshot from 2020-01-26 22-29-34](https://user-images.githubusercontent.com/54547503/73138676-740f1a00-408b-11ea-96a2-6b2b3a6c72fe.png)

**Comment by mayursamnani36** [comment]
I am taking up this issue

**Comment by laksh22** [comment]
@mayursamnani36 Are you still working on this issue? I would like to take it up if you're not working on it as of now.

**Comment by mayursamnani36** [comment]
Yes @laksh22 you can take this issue. Sorry for the trouble.
