### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/LabelLab#259]
**Is your feature request related to a problem? Please describe.**
Allow users to change password if they have forgotten their old one. 

**Describe the solution you'd like**
Send an email to their registered account giving them a link to change their password

**Additional context**
looking into it

**Comment by Rupeshiya** [comment]
are you working on it @carpecodeum ??

**Comment by carpecodeum** [comment]
@Rupeshiya yes i am currently working on it

**Comment by carpecodeum** [comment]
@UdeshUK I need a suggestion after thinking a lot on it I have two options to store the reset password token one create a separate model for it containing the user._id, the resetPasswordToken the expiration time and the status whether the user has applied for reset password before or add the same columns in the user table itself. What do you suggest?
