### ISSUE TITLE
"Back to Project" button in the labeller

### ISSUE THREAD

**Issue by laksh22** [scorelab/LabelLab#261]
**Is your feature request related to a problem? Please describe.**
The labeller does not seem to have a button to go back to the project. I currently have to either change the URL or press the back button in the browser which can take multiple presses if more than one image was labelled.

![labeller](https://user-images.githubusercontent.com/9462834/73546585-74872680-4478-11ea-8d68-c747887a7f7d.PNG)

**Describe the solution you'd like**
A "Back to Project" button in the labeller which takes the user back to the project which is being labelled.

**Describe alternatives you've considered**
The current "Back" button can also go back to the project if the current image is the first in the list.

**Additional context**
I am unsure if this feature doesn't exist or if there is a problem in my system due to which I am unable to see the button. If someone can confirm that this feature doesn't exist, I will work on implementing it.

**Comment by mayursamnani36** [comment]
@laksh22 my labeller page is just showing a blank white screen i dont know why.

**Comment by laksh22** [comment]
Hi @mayursamnani36, your error should be fixed once PR #185 is accepted.
