### ISSUE TITLE
Rewrite the backend in Flask

### ISSUE THREAD

**Issue by ivantha** [scorelab/LabelLab#283]

**Comment by carpecodeum** [comment]
@ivantha Hello sir, can you provide some details whether this will be related to a project idea for gsoc 2020? I am very excited to work on this!

**Comment by carpecodeum** [comment]
@ivantha which database are you thinking of using? are we continuing with mongodb?

**Comment by Nishaanthan** [comment]
@ivantha Hi I'm interested to take over this project for GSOC 2020. I have a good experience in flash and I can rewrite this backend in Flask
