### ISSUE TITLE
Implement a pipeline to run classification tasks using the images in the database

### ISSUE THREAD

**Issue by ivantha** [scorelab/LabelLab#285]

**Comment by laksh22** [comment]
@ivantha Would "classification tasks" include just image classification or would object detection also be included, since the current labelling tool allows multiple bounding boxes in the same image.

**Comment by 2knal** [comment]
Adding to what @laksh22 pointed out, what all classification modules should be implemented in the pipeline?

Thanks!

**Comment by Khalifa1997** [comment]
I would love to work on this task however can you point me out to the images in the database and are we allowed to use image processing techniques before passing the data to our model
Thanks

**Comment by sonishreyas** [comment]
I would like to work on this task.
