### ISSUE TITLE
Improvements to mobile image labelling tool

### ISSUE THREAD

**Issue by UdeshUK** [scorelab/LabelLab#289]
Following features should be implemented

- Cropping and resize images
- Editing and resizing of drawn selections
- Editing previous labels including their selection areas

**Comment by Dolar1** [comment]
hello @UdeshUK I am interested in continuing with the project for  GSOC 2020. It would be of great help to me if I can know more about it.

**Comment by UdeshUK** [comment]
@Dolar1 you can join the labellab [gitter chat](https://gitter.im/scorelab/LabelLab). You can ask any questions or get support from there
