### ISSUE TITLE
Complete the documentation of the project

### ISSUE THREAD

**Issue by ivantha** [scorelab/labellab#291]
Complete documentation on the project should be provided along with a deployed demo in the gcp.

**Comment by abhhii** [comment]
HI I would like to work on this for gsoc 2020. Please direct me on how to start working on it.

**Comment by Semicolon10** [comment]
Can I take this issue

**Comment by tanvidhope** [comment]
Hey @ivantha I would like to take up this issue for gsoc. Can you please tell me what to do?
