### ISSUE TITLE
SHA1 fingerprint addition description ambiguous in Readme.md under How to Use (Mobile)

### ISSUE THREAD

**Issue by ov1n** [scorelab/LabelLab#300]
**Is your feature request related to a problem? Please describe.**
The method for SHA1 fingerprint generation in Firebase when obtaining the `google-services.json` file is unclear to a certain extend

**Describe the solution you'd like**
Under the same point (**6.Get the SHA1 fingerprint by following the instruction...**) add a more descriptive walk-through.

**Describe alternatives you've considered**
Include a link to an external site to which shows how to generate SHA1 fingerprint.

**Additional context**

**Comment by Shrawan907** [comment]
`keytool -list -v -alias androiddebugkey -keystore %USERPROFILE%\.android\debug.keystore`
run this command in terminal in your project directory
and use "android" as default password

**Comment by UdeshUK** [comment]
#313 fixed this issue
