### ISSUE TITLE
App splash-screen logo not viewed properly in some mobile devices

### ISSUE THREAD

**Issue by ov1n** [scorelab/LabelLab#333]
**Describe the bug**
The starting app logo screen is not scaled properly when displayed in most devices (Any mobile device without  native resolution aspect ratio 16:9)

**To Reproduce**
1. Simply launch the app in a physical device as the emulator.

**Expected behavior**
`drawable/pro.png` image to be shown incompletely or scaled.

**Screenshots**
[Oneplus 5T](https://drive.google.com/open?id=1LrvnY4JfjvYstVoGsKuhb-fwx9daU47v)

**Smartphone (please complete the following information):**
 - Device: Oneplus 5T
 - OS: Android 9
 - Phone resolution: 1080 x 2160
 - Aspect Ratio: 18:9

**Additional context**
Can be fixed if option added to scale images based on each phone's screen resolution.
(`stack` or `container` options on the widget)

**Comment by UdeshUK** [comment]
This issue is fixed on #304. Reopen issue if the bug still exists.
