### ISSUE TITLE
Add a close button in labeller app

### ISSUE THREAD

**Issue by nguptaa** [scorelab/LabelLab#348]
**Is your feature request related to a problem? Please describe.**
There is no way to go home or to the previous page, once a person starts to edit/label a picture.

**Describe the solution you'd like**
Adding a close button just right to the keyboard icon.

**Describe alternatives you've considered**
Feature of going back to the previous page when the user clicks on the Back button on the first image he opened in the app.

**Screenshot**

![Screenshot 2020-03-18 at 11 07 01 PM](https://user-images.githubusercontent.com/22504975/76989417-67fa5700-696e-11ea-88ea-c19d81e6f831.png)

**Comment by cazci** [comment]
Thank you @nguptaa for pointing this out. But can you please be more specific on the issue. There is a back arrow on every screen (on its App bar) and its functionality is to go back to the previous screen. Maybe I can't clearly understand where you are referring. Can you add a screenshot to be more clear?

**Comment by nguptaa** [comment]
@cazci I mean we can go to next and previous image. But when we are on the image we initially opened in-app while for labelling, we can't go back/previous from there.

I've added a screenshot to make it more clear.

**Comment by thivatm** [comment]
@nguptaa Do you mean that we cant exit from that page while drawing boundary boxes in the images?

**Comment by laksh22** [comment]
Issue #261 already exists which addresses this problem.
