### ISSUE TITLE
Error while registering!

### ISSUE THREAD

**Issue by msk4862** [scorelab/LabelLab#35]
I've successfully connected to mongodb and started lablabel-server and client but I'm getting following error while registering a user.

**Unhandled Rejection (TypeError): Cannot read property 'msg' of null
C:/Users/msk/Desktop/open_source/LabelLab/labellab-client/src/actions/index.js:74**

![bug](https://user-images.githubusercontent.com/24875366/59500253-b138ea00-8eb6-11e9-8804-fbcf29c9a199.png)

**Comment by Tushar19varshney** [comment]
@msk4862 I have updated the code and implemented checks on passing arguments.
