### ISSUE TITLE
dbURI.js Not configured

### ISSUE THREAD

**Issue by Semicolon10** [scorelab/LabelLab#369]
**Describe the bug**
dbURI.js file contains MongoDB connection String which contains developers private information like database username, password etc. 

**To Reproduce**
1. Go to 'LabelLab\labellab-server\config\dbURI.js'
3. Scroll down to 'Line13'
4. See the connection string

**Expected behavior**
The dbURI.js file should be added into git ignore after creating dbURI.js.example file. So new users can setup their environment by looking at the .example file.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/29561593/77219643-be79b800-6b5d-11ea-8dd5-b360af150cd4.PNG)

**Comment by UdeshUK** [comment]
This issue is fixed
