### ISSUE TITLE
Mobile App: Improve UX using animations

### ISSUE THREAD

**Issue by cazci** [scorelab/LabelLab#378]
**Is your feature request related to a problem? Please describe.**
It's better if the app may have more attractive animations that give the user a pleasant experience. 

**Describe the solution you'd like**
Ux can be improved by using natural fluid animations. As the first stage, I would like to suggest adding animations to the user profile screen. 

**Describe alternatives you've considered**
N/A

**Additional context**
I would like to work on this update.

**Comment by UdeshUK** [comment]
@cazci are you working on this?

**Comment by cazci** [comment]
No, I reverted back the changes I've done. I'll close this issue for now.
