### ISSUE TITLE
Error appearing on the Project Analytics page when there are no labels

### ISSUE THREAD

**Issue by DonOmalVindula** [scorelab/LabelLab#386]
**Describe the bug**
An error will show up in the console when Project Analytics page is viewed without any labels.

**To Reproduce**
1. Create a new project by clicking on "Start New Project"
2. Click on the project card in the dashboard
3. Click on "Project Analytics" from the sidebar

**Expected behaviour**
An error should not appear on the console when Project Analytics is viewed without any labels.

**Screenshots**
![image](https://user-images.githubusercontent.com/42619922/77283789-3b8a6600-6cf3-11ea-9f66-d78e94c79062.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Home
 - Browser: Chrome
 - Version: 80

**Additional context**
I will be working on this issue.

**Comment by AkMo3** [comment]
@amlannandy This issue is resolved. Please close the issue.
