### ISSUE TITLE
Add Select all images radio button feature to delete all images at once

### ISSUE THREAD

**Issue by nguptaa** [scorelab/labellab#390]
**Is your feature request related to a problem? Please describe.**
Individual deletion of images becomes cumbersome task hence select all and then delete feature comes handy.

**Describe the solution you'd like**
Implement a radio button that on click selects all images and the deletes it on a click.

**Screenshot**
Like this one!
![Screenshot 2020-03-24 at 10 06 07 AM](https://user-images.githubusercontent.com/22504975/77388374-04ca5380-6db8-11ea-97b0-1483a16c9965.png)

**Comment by Semicolon10** [comment]
Can I take this issue

**Comment by nguptaa** [comment]
> Can I take this issue

I'm working on it. If I get busy in some work and couldn't fix it by evening I will let you know :)
