### ISSUE TITLE
[feature] Write backend in django and django rest framework

### ISSUE THREAD

**Issue by Tushar19varshney** [scorelab/LabelLab#398]
This issue is just for discussion about backend framework. We are thinking to write backend of LabelLab in [Django](https://docs.djangoproject.com/en/3.0/) as it really simple, flexible, widely used framework. All of you are welcome to contribute in the discussion.

**Comment by carpecodeum** [comment]
I agree with you I think django can be a better option for rewriting the backend on. The advantages of Django over Flask are obvious. It provides massively more functionality out of the box, has a much richer ecosystem, and is used for more larger projects, and comes with really smart security defaults that will almost certainly make your app more secure than the app you're going to write in Flask.

**Comment by carpecodeum** [comment]
One of the features of Django that can come in handy to us is the django admin. Which can help the project admin to manage his projects and the project members easily. At the same time, the ORM system provided by Django makes it easier for programmers to work with several widely used databases. They can even use the ORM system to perform common database operations and migrate from one database to another without writing additional code.

**Comment by Semicolon10** [comment]
I think we should go with whatever framework rather than discussing it flask or django both frameworks are powerful and both are capable for our requirement I guess

**Comment by laksh22** [comment]
Given that Django has a lot more functionality built-in and also has a bigger community than Flask, I also think Django would be the way to go since it would not only be beneficial for the project but would also benefit new contributors.

**Comment by Tushar19varshney** [comment]
I am closing this issue as we have decided to shift on flask. Thanks @laksh22 @carpecodeum for your suggestions.
