### ISSUE TITLE
GSOC 2019 Idea 

### ISSUE THREAD

**Issue by vinay72** [scorelab/LabelLab#4]
@ivantha According to the Official GSOC-2019 list of project ideas of Score Lab , there is one Idea which is on Implementing the Label Lab Web Application . I want to work on this Idea and want to take part in GSOC-2019 . I have already introduced myself on Gitter.

**Comment by nikhilagrawal2000** [comment]
@ivantha I want to work on the Label Lab Mobile Application in GSoC 2019. It would be great if you can guide me through it. Thanks!!

**Comment by shreya2feb** [comment]
@vinay72 @nikhilagrawal2000 It is great that you want to contribute to labellab, for more info regarding this project join labellab gitter channel [here](https://gitter.im/scorelab/LabelLab).
there is a small task to be completed for selection
link in [here](https://docs.google.com/document/d/1-KzFWyu6pwGBG1NXveiIWJy1BIpCDx7D2rPegmz8yzM/edit?usp=sharing)

happy coding :)

**Comment by vinay72** [comment]
@shreya2feb Thanks for Replying.
