### ISSUE TITLE
Show image number when labeling images

### ISSUE THREAD

**Issue by laksh22** [scorelab/LabelLab#403]
**Is your feature request related to a problem? Please describe.**
When multiple images have to be labeled, it would be better if the user could tell how many images were left to be labeled.

**Describe the solution you'd like**
While labeling, the sidebar should show the image number and the total number of images. For example if there are a total of 25 images and the user is currently on image number 6, the sidebar could show __6/25__.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Tushar19varshney** [comment]
@laksh22 This issue is addressed by @carpecodeum. I am closing this one.
