### ISSUE TITLE
Make button colors uniform based on functionality

### ISSUE THREAD

**Issue by laksh22** [scorelab/LabelLab#405]
**Describe the bug**
Most of the buttons in the client perform 3 functions: Addition, Deletion, and Editing. In the current implementation, the buttons do not have a uniform color scheme. It would be better for the user experience if buttons were colored consistently based on their functionality.

**To Reproduce**
1. Create a new project
2. Open the __Project Team__ tab and notice the color of the __Add member__ button is `00a89f`
3. Open the __Project Images__ tab and notice the color of the __Add Image__ button is blue

**Expected behavior**
The buttons should be colored based on their functionality in a consistent manner:
> Addition - `positive`
> Deletion - `negative`
> Editing - default

**Screenshots**
Add member, Add Image, and Add Label, all of different colours:
![1](https://user-images.githubusercontent.com/9462834/78420850-adfd2d80-7685-11ea-93cc-30f67023086a.PNG)
![22](https://user-images.githubusercontent.com/9462834/78420855-b0f81e00-7685-11ea-95f2-67c0ecac780c.PNG)
![3](https://user-images.githubusercontent.com/9462834/78420856-b2c1e180-7685-11ea-8f99-56428fe0639c.PNG)

**Additional context**
Working on it

**Comment by Tushar19varshney** [comment]
@laksh22 If you created some mockup regarding this, you can add those here so that everyone can have suggestions on them.

**Comment by laksh22** [comment]
@Tushar19varshney Something like this:
![new_buttons](https://user-images.githubusercontent.com/9462834/82571699-ea450880-9bb5-11ea-95a2-5d77e6aa8a1f.PNG)
