### ISSUE TITLE
Login button not working

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/LabelLab#410]
**Describe the bug**
The login button is not logging the user in.

**To Reproduce**
1. Go to 'login page'
2. Enter credentials
3. Click on login

**Expected behavior**
The user should have logged in.

**Additional context**
working on it

**Comment by laksh22** [comment]
Have you made sure the user exists in your database? The login button seems to be working for me with the latest code

**Comment by Tushar19varshney** [comment]
@carpecodeum I think this issue is no longer relevant. Should I close this?

**Comment by carpecodeum** [comment]
Yes i think we can close this
