### ISSUE TITLE
Can't resolve 'react-image-lightbox'

### ISSUE THREAD

**Issue by Semicolon10** [scorelab/LabelLab#417]
**Describe the bug**
In the last merge 'react-image-lightbox' pm package installed without updating into the dependencies

**To Reproduce**
1. Go to the labellab-server
2. run the command npm run dev
3. Go to the localhost and refresh

**Expected behavior**
Load  the page without error

**Screenshots**
![Capture](https://user-images.githubusercontent.com/29561593/79683281-a4a7bf80-8246-11ea-91d6-a8fbf6a63e52.PNG)

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser chrome
 - Version latest

**Comment by carpecodeum** [comment]
did you run npm install?

**Comment by Semicolon10** [comment]
> did you run npm install?

Yes. by the way `npm i react-image-lightbox` sloved the thing. I posted the issue because my new pull request will take some time to merge

**Comment by carpecodeum** [comment]
> > did you run npm install?
> 
> Yes. by the way `npm i react-image-lightbox` sloved the thing. I posted the issue because my new pull request will take some time to merge

The package is already in package.json so even if you run npm install in the client it would fix the problem.

**Comment by Semicolon10** [comment]
oh really 

> > > did you run npm install?
> > 
> > 
> > Yes. by the way `npm i react-image-lightbox` sloved the thing. I posted the issue because my new pull request will take some time to merge
> 
> The package is already in package.json so even if you run npm install in the client it would fix the problem.

oh really, then it can be some problem with my latest pull from the master. anyway then I'm closing the issue thanks fro letting me know
