### ISSUE TITLE
Padding/Margin issue when returning from project/profile to dashboard

### ISSUE THREAD

**Issue by laksh22** [scorelab/LabelLab#419]
**Describe the bug**
When the user is on a project page and clicks on the __Dashboard__ button in the navbar, the dashboard that opens up has no margin/padding to the left. The margin/padding returns after refreshing the page. The same thing happens if returning from the profile page.

**To Reproduce**
1. Select one of your projects from the dashboard
2. Wait for the project page to load
3. Click on the __Dashboard__ button in the navbar to go back

**Expected behavior**
The padding/margin on the dashboard page should be normal when the user returns from a project page.

**Screenshots**
![misaligned](https://user-images.githubusercontent.com/9462834/79851965-9b5e5480-83f8-11ea-9959-cf2ea3ca446d.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81

**Additional context**
N/A

**Comment by Tushar19varshney** [comment]
@laksh22 Are you working on this issue? I think this issue is occurring due to class overriding.

**Comment by laksh22** [comment]
@Tushar19varshney Fixed the issue in PR #431
