### ISSUE TITLE
Unable to login due to form validation

### ISSUE THREAD

**Issue by laksh22** [scorelab/LabelLab#488]
**Describe the bug**
After creating a new user, the __Log In__ button does not work nothing changes on the page.

**To Reproduce**
1. Create a new user
2. Go to the login page
3. Enter the credentials of the new user
4. Press the login button and see error

**Expected behavior**
The login button should login the user and show the dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/9462834/87938406-223ece00-cac9-11ea-90a1-f4b6da9bb45c.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 83

**Additional context**
This problem occurs because of the `validateForm(this.state)` condition on the login page.

**Comment by temanisparsh** [comment]
Hey, I would like to work on this issue. Can I take this up ?

**Comment by laksh22** [comment]
@temanisparsh Sure, go ahead
