### ISSUE TITLE
Fix the 'Dashboard' sign to redirect to the dashboard.

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/LabelLab#509]
**Describe the bug**
fix the dashboard to go back to the dashboard or "/". Currently it does not lead to anywhere.

**To Reproduce**
1. Go to 'Projects page'
2. Click on 'Dashboard'
3. See error

**Expected behavior**
The dashboard button should lead to the dashboard or "/".

**Screenshots**
![Screenshot 2020-08-23 at 1 18 18 PM](https://user-images.githubusercontent.com/43586052/90973852-8418aa80-e543-11ea-8437-6d8a441008f3.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by temanisparsh** [comment]
@carpecodeum This seems to happen because of a simple overlap between the Search Bar and the Dashboard Button. Increasing the `z-index` should work.
