### ISSUE TITLE
Fix thew search Images search bar

### ISSUE THREAD

**Issue by carpecodeum** [scorelab/LabelLab#510]
**Describe the bug**
Fix the search images search bar.

**To Reproduce**
1. Go to 'Projects page'
2. Click on 'search image'
3. See error

**Expected behavior**
It should work fine

**Screenshots**
![Screenshot 2020-08-23 at 1 24 24 PM](https://user-images.githubusercontent.com/43586052/90973910-fdb09880-e543-11ea-9c84-480906e4a5f7.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by temanisparsh** [comment]
@carpecodeum This issue seems to occur because of the fact that the ```createdAt``` field was removed in the Flask Server models but is present in the initial node-mongo API model. A simple fix would be to either get rid of the ```createdAt``` field completely in the client or add in a new field in the image table on server side.

**Comment by carpecodeum** [comment]
> @carpecodeum This issue seems to occur because of the fact that the ```createdAt``` field was removed in the Flask Server models but is present in the initial node-mongo API model. A simple fix would be to either get rid of the ```createdAt``` field completely in the client or add in a new field in the image table on server side.

@temanisparsh I think removing it would be a better idea. But you would have to order it in some or the other way. Give it a shot :)

**Comment by temanisparsh** [comment]
@carpecodeum Sure, will work on this. The images can be ordered with respect to the ID instead of dates, serves the same purpose in this case.
