### ISSUE TITLE
Show password button triggers authenticating loader.

### ISSUE THREAD

**Issue by pranay-simejia** [scorelab/labellab#536]
**Describe the bug**
On clicking the eye icon on show password button, it start showing authenticating loader.

**To Reproduce**
1. Go to '/login'
2. Click on 'eye icon button'
3. See error authentication loader screen

**Expected behavior**
On clicking the show password button, it should just toggle the state of the password field. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pranay-simejia** [comment]
Can I start working on this issue?

**Comment by carpecodeum** [comment]
sure @pranay-simejia

**Comment by pranay-simejia** [comment]
hey @carpecodeum solved this, but discovered a very strange issue, on **hitting enter in the input fields it would toggle the showPassword state.** Tried hard but wasn't able to figure out. Can you **help** me?

**Comment by pranay-simejia** [comment]
@carpecodeum can you review my PR please?
