### ISSUE TITLE
[Web] Delete image and refresh on adding image funtionality not working

### ISSUE THREAD

**Issue by darkshredder** [scorelab/labellab#547]
**Describe the bug**
Currently when we click on deleting an image in a project. It is not working and on adding an image to the project without refreshing new image is not being show.

**To Reproduce**
1.Sign in to your account
2. Open any project or create a new one
3. Click on Project Images on the sidebar
4. Add an image and see that image is added but it's not automatically refreshing
5. Try on deleting an image.
6. Deleting is not working at all

**Expected behavior**
Deleting image should work and state of project should be refreshed

**Additional context**
I would like to Work on this.

**Comment by carpecodeum** [comment]
sure @darkshredder
