### ISSUE TITLE
fix: MONGODB_URI field is not mentioned in .env inside labellab-server

### ISSUE THREAD

**Issue by sachinsom93** [scorelab/labellab#564]
**Describe the bug**
In labellab-server/.env file, a field named as MONGODB_URI should be mentioned for mongodb connection string, as this field is checked inside labellab-server/config/dbURL.js file in line no.15.

**Screenshots**
screenshot of labellab-server/config/dbURL.js file
 ![config/dbURL.js](https://github.com/sachinsom93/temp/blob/master/mongoURI.jpg?raw=true)

screenshot of .env file
![.env file](https://github.com/sachinsom93/temp/blob/master/.env.jpg?raw=true)

**To Reproduce**
1. Go to 'labellab-server/.env'
2. Add MONGODB_URI field 

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by carpecodeum** [comment]
Closed as we dont use a node-based server for the backend now
