### ISSUE TITLE
Separate readme file for flask-server and node-server

### ISSUE THREAD

**Issue by sachinsom93** [scorelab/LabelLab#566]
**Is your feature request related to a problem? Please describe.**
There should be a separate README file for node-server and flask-server.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Can I work on this issue ?

**Comment by carpecodeum** [comment]
sure

**Comment by carpecodeum** [comment]
I don't think so that is required, though if you want to make documentation for the endpoints there is a setup for sphinx documentation in the flask server. Follow the sphinx guidelines and make the endpoint documentation. This can be a good issue to solve.

**Comment by sachinsom93** [comment]
Ok, will genarate a PR soon, thanks @carpecodeum.
