### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by akash2237778** [scorelab/LabelLab#587]
**Describe the bug**
Build failed with an exception.

**To Reproduce**
1. Setup Config.dart, google-services.json and Maps Key in Android.xml
2. Run 'flutter pub get'
2. Run 'flutter run'

**Expected behavior**
It shows there is some problem with provider package. Might be due to a deprecated package explained better in screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/46739435/111894095-ee3bf400-8a2d-11eb-96f4-6e77e95c3ea5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - IDE: VSCode
 - Flutter Version: Flutter 2.0.1

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android
 - Browser: Chrome
 - Android Version: 10

**Comment by amlannandy** [comment]
@akash2237778 Hey! This seems to be a problem with using Flutter 2.0. The same thing happened to me. Downgraded to 1.22.6 and it works fine.

**Comment by akash2237778** [comment]
@amlannandy not working even with flutter version 1.22.6
