### ISSUE TITLE
Implement backend service selection to authentication flow of mobile application

### ISSUE THREAD

**Issue by Useful-Ad-1249** [scorelab/LabelLab#597]
Currently, the mobile project should be set up in a development environment and built for every instance of a backend service. 

Instead, a feature should be added to enter the backend service (API BASE URL) prior to the authentication flow. Thus, a user can download a prebuild APK of the mobile application and use it with any backend instance.

**Comment by UdeshUK** [comment]
> @UdeshUK Hello! Can I work on this now and submit a PR? Or is it reserved to be done during GSOC only?

Good to see the enthusiasm, but we'll keep this for GSoC.
