### ISSUE TITLE
Update documentation to add CMake as requirements for labellab-flask

### ISSUE THREAD

**Issue by AkMo3** [scorelab/LabelLab#620]
**Describe the bug**
When CMake is not installed in the system, pip fails to install the requirements.txt. Add in the documentation that **CMake is a requirement**.

**To Reproduce**
1. `cd labellab-flask`
2. Remove CMake (Possibly using : `snap remove cmake`)
3. `pip install -r requirements.txt`

**Expected behavior**
CMake as a requirement in the documentation.

**Screenshots**
![image](https://user-images.githubusercontent.com/69365878/157447203-58be1aa8-ca38-4cf7-8cfd-0d368f5ee269.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: NA
 - Version: NA

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AkMo3** [comment]
@amlannandy Can you approve the issue so that I can start working on it?

**Comment by amlannandy** [comment]
@AkMo3 Yes you can start working on it

**Comment by AkMo3** [comment]
Can you please provide me access to edit the wiki page?
I got to know that only repo owners and collaborators can edit it with default permission. Here is the link on how to edit permission: [Chaning access permission for wikis](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis)

**Comment by amlannandy** [comment]
I forgot that we have the docs in the wiki instead of readme. Unfortunately, we can give repo access to org members only. You can drop this issue. I'll update the wiki myself.
