### ISSUE TITLE
Old version of Flask Packages

### ISSUE THREAD

**Issue by M-A-D-A-R-A** [scorelab/LabelLab#632]
**Is your feature request related to a problem? Please describe.**
While trying to connect to the MySQL and im getting this error , i looked it up and this is because we are using older version of Flask-JWT-Extended==3.24.1 and the new compatible version (Flask-JWT-Extended==4.3.1) doesnt support jwt_refresh_token_required, im still not able to run my flask server.
![image](https://user-images.githubusercontent.com/56160262/159173443-91271065-93a2-49e8-bfe2-d4031fd9dfd1.png)

**Describe the solution you'd like**
Also there are many packages that are either updated or deprecated it will be good if we keep our packages upto date.

**Describe alternatives you've considered**
Like we can create a parent issue for all the packages and in chikd issue we update one -one packages to be updated and update them in each issue.

**Comment by amlannandy** [comment]
Fixed with documentation update
